# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "dev_srv" do |dev_srv|
    dev_srv.vm.box = "ubuntu/trusty64"
    dev_srv.vm.provider "virtualbox" do |vb|
       vb.memory = 1024
       vb.cpus = 1
     end
     dev_srv.vm.host_name = "e-www"
     dev_srv.vm.network "private_network", ip: "192.168.200.10"
     dev_srv.vm.synced_folder "..", "/e_www"
     dev_srv.vm.provision "shell", path:"bootstrap.sh"
   end
end